# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BILLETERA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PIN', models.CharField(max_length=50)),
                ('saldo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ofrece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PERFIL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asd', models.DateTimeField(auto_now_add=True)),
                ('pseudonimo', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PLATO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RESTAURANT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('RIF', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TRANSACCION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('billetera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.BILLETERA')),
            ],
        ),
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('contrasenia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CLIENTE',
            fields=[
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.USUARIO')),
                ('ci', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('billetera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.BILLETERA')),
            ],
        ),
        migrations.CreateModel(
            name='INTERES_PERFIL',
            fields=[
                ('perfil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.PERFIL')),
                ('interes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PROVEEDOR',
            fields=[
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.USUARIO')),
                ('rif', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TELEFONOS_RESTAURANT',
            fields=[
                ('establecimiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.RESTAURANT')),
                ('telefono', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PERFIL'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='establecimiento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.RESTAURANT'),
        ),
        migrations.AddField(
            model_name='plato',
            name='establecimiento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.RESTAURANT'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='establecimiento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.RESTAURANT'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PRODUCTO'),
        ),
        migrations.AddField(
            model_name='ofrece',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PRODUCTO'),
        ),
        migrations.AddField(
            model_name='menu',
            name='establecimiento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.RESTAURANT'),
        ),
        migrations.AddField(
            model_name='menu',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PLATO'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='establecimiento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.RESTAURANT'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PRODUCTO'),
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='plato_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PLATO'),
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PRODUCTO'),
        ),
        migrations.AlterUniqueTogether(
            name='transaccion',
            unique_together=set([('establecimiento_id', 'billetera_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='plato',
            unique_together=set([('establecimiento_id', 'nombre')]),
        ),
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PROVEEDOR'),
        ),
        migrations.AddField(
            model_name='ofrece',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PROVEEDOR'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([('establecimiento_id', 'plato')]),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together=set([('establecimiento_id', 'producto_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientes',
            unique_together=set([('plato_id', 'producto_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='pedido',
            unique_together=set([('establecimiento_id', 'producto_id', 'email')]),
        ),
        migrations.AlterUniqueTogether(
            name='ofrece',
            unique_together=set([('email', 'producto_id')]),
        ),
    ]
