# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BILLETERA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PIN', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('saldo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MENU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, validators=[menu.models.validate_nombre])),
            ],
        ),
        migrations.CreateModel(
            name='Ofrece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PERFIL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pseudonimo', models.CharField(max_length=100, unique=True)),
                ('foto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PLATO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, validators=[menu.models.validate_nombre])),
                ('precio', models.FloatField()),
                ('path_img', models.FileField(upload_to='')),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Plato_en_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MENU')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PLATO')),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RESTAURANT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, validators=[menu.models.validate_nombre])),
                ('RIF', models.CharField(max_length=50, unique=True, validators=[menu.models.validate_rif])),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TRANSACCION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('billetera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.BILLETERA')),
            ],
        ),
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('contrasenia', models.CharField(max_length=50)),
                ('es_cliente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CLIENTE',
            fields=[
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.USUARIO')),
                ('ci', models.CharField(max_length=50, unique=True, validators=[menu.models.validate_ci])),
                ('nombre', models.CharField(max_length=50, validators=[menu.models.validate_nombre])),
                ('apellido', models.CharField(max_length=50, validators=[menu.models.validate_nombre])),
                ('telefono', models.CharField(max_length=50, validators=[menu.models.validate_telefono])),
                ('fechaNacimiento', models.DateField()),
                ('billetera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.BILLETERA')),
            ],
        ),
        migrations.CreateModel(
            name='INTERES_PERFIL',
            fields=[
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.PERFIL')),
                ('interes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PROVEEDOR',
            fields=[
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.USUARIO')),
                ('rif', models.CharField(max_length=50, unique=True, validators=[menu.models.validate_rif])),
                ('nombre', models.CharField(max_length=50, validators=[menu.models.validate_nombre])),
            ],
        ),
        migrations.CreateModel(
            name='TELEFONOS_RESTAURANT',
            fields=[
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.RESTAURANT')),
                ('telefono', models.CharField(max_length=50, unique=True, validators=[menu.models.validate_telefono])),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PERFIL'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.RESTAURANT'),
        ),
        migrations.AddField(
            model_name='plato',
            name='establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.RESTAURANT'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.RESTAURANT'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PRODUCTO'),
        ),
        migrations.AddField(
            model_name='ofrece',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PRODUCTO'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.RESTAURANT'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PRODUCTO'),
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PLATO'),
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PRODUCTO'),
        ),
        migrations.AlterUniqueTogether(
            name='transaccion',
            unique_together=set([('establecimiento', 'billetera')]),
        ),
        migrations.AlterUniqueTogether(
            name='plato_en_menu',
            unique_together=set([('plato', 'menu')]),
        ),
        migrations.AlterUniqueTogether(
            name='plato',
            unique_together=set([('establecimiento', 'nombre')]),
        ),
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PROVEEDOR'),
        ),
        migrations.AddField(
            model_name='ofrece',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PROVEEDOR'),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together=set([('establecimiento', 'producto')]),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientes',
            unique_together=set([('plato', 'producto')]),
        ),
        migrations.AlterUniqueTogether(
            name='pedido',
            unique_together=set([('establecimiento', 'producto', 'email')]),
        ),
        migrations.AlterUniqueTogether(
            name='ofrece',
            unique_together=set([('email', 'producto')]),
        ),
    ]
