# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20160601_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
