# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20160601_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='pseudonimo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
