# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20160601_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='email',
            new_name='usuario',
        ),
    ]
