# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20160601_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_cliente',
            field=models.BooleanField(default=False),
        ),
    ]
