# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_usuario_es_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato_en_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='plato_en_menu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MENU'),
        ),
        migrations.AddField(
            model_name='plato_en_menu',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PLATO'),
        ),
        migrations.RemoveField(
            model_name='menu',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='plato',
        ),
        migrations.AlterUniqueTogether(
            name='plato_en_menu',
            unique_together=set([('plato', 'menu')]),
        ),
    ]
