# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20160602_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='nombre',
            field=models.CharField(default='sinnombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plato_en_menu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MENU'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
