# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_auto_20160608_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fechaNacimiento',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=50, validators=[menu.models.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ci',
            field=models.CharField(max_length=50, unique=True, validators=[menu.models.validate_ci]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50, validators=[menu.models.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=50, validators=[menu.models.validate_telefono]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='nombre',
            field=models.CharField(max_length=100, validators=[menu.models.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre',
            field=models.CharField(max_length=50, validators=[menu.models.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='plato_en_menu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MENU'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=50, validators=[menu.models.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rif',
            field=models.CharField(max_length=50, unique=True, validators=[menu.models.validate_rif]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='RIF',
            field=models.CharField(max_length=50, unique=True, validators=[menu.models.validate_rif]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='nombre',
            field=models.CharField(max_length=50, validators=[menu.models.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='telefonos_restaurant',
            name='telefono',
            field=models.CharField(max_length=50, unique=True, validators=[menu.models.validate_telefono]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
