# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_auto_20160606_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=50, validators=[menu.models.validate_telefono]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='nombre',
            field=models.CharField(max_length=100, validators=[menu.models.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre',
            field=models.CharField(max_length=50, validators=[menu.models.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='plato_en_menu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MENU'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=50, validators=[menu.models.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rif',
            field=models.CharField(max_length=50, unique=True, validators=[menu.models.validate_rif]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='RIF',
            field=models.CharField(max_length=50, unique=True, validators=[menu.models.validate_rif]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='nombre',
            field=models.CharField(max_length=50, validators=[menu.models.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='telefonos_restaurant',
            name='telefono',
            field=models.CharField(max_length=50, unique=True, validators=[menu.models.validate_telefono]),
        ),
    ]
