# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_auto_20160608_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fechaNacimiento',
            field=models.DateField(default=1, verbose_name=0.0010256410256410256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plato_en_menu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MENU'),
        ),
    ]
