# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_auto_20160606_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='billetera',
            name='apellido',
            field=models.CharField(default='a', max_length=50, validators=[menu.models.validate_nombre]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billetera',
            name='nombre',
            field=models.CharField(default='a', max_length=50, validators=[menu.models.validate_nombre]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plato_en_menu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MENU'),
        ),
    ]
