# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0064_auto_20160609_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.RESTAURANT'),
        ),
        migrations.AlterField(
            model_name='plato_en_menu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MENU'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.RESTAURANT'),
        ),
    ]
