# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0065_auto_20160609_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato_en_menu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MENU'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.FloatField(validators=[menu.models.validate_monto]),
        ),
    ]
