# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0067_auto_20160609_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofrece',
            old_name='email',
            new_name='proveedor',
        ),
        migrations.AlterField(
            model_name='plato_en_menu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MENU'),
        ),
        migrations.AlterUniqueTogether(
            name='ofrece',
            unique_together=set([('proveedor', 'producto')]),
        ),
    ]
