# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0072_auto_20160623_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEDIDOPROVEEDOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PROVEEDOR')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEnPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PEDIDOPROVEEDOR')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Ofrece')),
            ],
        ),
        migrations.AlterField(
            model_name='plato_en_menu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MENU'),
        ),
    ]
