# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0073_auto_20160629_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plato_en_menu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MENU'),
        ),
    ]
