# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0076_auto_20160629_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.CharField(max_length=3)),
                ('comentario', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='plato',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plato_en_menu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MENU'),
        ),
        migrations.AddField(
            model_name='puntacion',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.PLATO'),
        ),
        migrations.AddField(
            model_name='puntacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.USUARIO'),
        ),
    ]
