# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0079_auto_20160629_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato_en_menu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MENU'),
        ),
        migrations.AlterField(
            model_name='puntuacion',
            name='puntuacion',
            field=models.CharField(max_length=5),
        ),
    ]
