# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0081_auto_20160701_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofrece',
            name='precio',
            field=models.FloatField(validators=[menu.models.validate_precio]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio',
            field=models.FloatField(validators=[menu.models.validate_precio]),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.FloatField(validators=[menu.models.validate_precio]),
        ),
        migrations.AlterField(
            model_name='plato_en_menu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MENU'),
        ),
    ]
